
#Each new term in the Fibonacci sequence
#is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not
#exceed four million, find the sum of the even-valued terms.

total_val = 0
val1 = 0
val2 = 1
val3 = 0

list = [1, 2]

for i in list:
    val3 = list[val1] + list[val2]
    if val3 < 4000000:
        list.append(val3)
    else:
        break
    val1 += 1
    val2 += 1

list2 = [i for i in list if i % 2 == 0]

for val in list2:
    total_val += val

print(total_val)
